apiVersion: v1
kind: ConfigMap
metadata:
  name: nomadd-configmap
  namespace: nomadd-stg
data:
  APP_NAME: "Laravel"
  APP_ENV: "local"
  APP_DEBUG: "true"
  APP_URL: "http://localhost"
  LOG_CHANNEL: "stack"
  LOG_LEVEL: "debug"

  AWS_DEFAULT_REGION: "us-east-1"
  AWS_BUCKET: ""
  AWS_USE_PATH_STYLE_ENDPOINT: "false"
  PUSHER_APP_ID: ""
  PUSHER_APP_CLUSTER: "mt1"
  MIX_PUSHER_APP_KEY: "${PUSHER_APP_KEY}"
  MIX_PUSHER_APP_CLUSTER: "${PUSHER_APP_CLUSTER}"

  GOOGLE_CLIENT_ID: "117658071339-ek1t6mmdb61m9j31r1701d9tn18d6mdv.apps.googleusercontent.com"
  GOOGLE_CLIENT_SECRET: "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"
  GOOGLE_CLIENT_REDIRECT: "http://localhost:8000/auth/google/callback"

  MIDTRANS_SERVERKEY: "SB-Mid-server-M5rMFkz8AwXEzUDGeAU8uoi0"
  MIDTRANS_CLIENTKEY: "SB-Mid-client-3Fj1-Dfeiz5GSIwd"
  MIDTRANS_IS_PRODUCTION: "false"
  MIDTRANS_IS_SANITIZED: "false"
  MIDTRANS_IS_3DS: "false"