apiVersion: v1
kind: Service
metadata:
  name: nomadd
  namespace: nomadd-stg
spec:
  selector:
    app: nomadd-stg
  ports:
    - port: 8000
      name: http
      protocol: TCP
      targetPort: 80
  type: NodePort