apiVersion: v1
kind: Pod
metadata:
  name: nomadd
  namespace: nomadd-stg
  labels:
    app: nomadd-stg
spec:
  initContainers:
    - name: artisan-migrate
      image: airist/nomadd:staging-65cfc6f
      command: [".docker/php-artisan-migrate"]
      env:
        - name: DB_HOST
          value: mysql-db
        - name: DB_PORT
          value: "3306"
        - name: DB_DATABASE
          valueFrom:
            configMapKeyRef:
              key: MYSQL_DATABASE
              name: mysql-config
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              key: MYSQL_USER
              name: mysql-secret
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: MYSQL_PASSWORD
              name: mysql-secret
  containers:
    - name: nomadd
      image: airist/nomadd:staging-65cfc6f
      imagePullPolicy: IfNotPresent
      resources:
        requests:
          cpu: 100m
          memory: 500Mi
        limits:
          cpu: 1500m
          memory: 1000Mi
      ports:
        - containerPort: 80
      envFrom:
        - configMapRef:
            name: nomadd-configmap
        - secretRef:
            name: nomadd-secret
      env:
        - name: APP_URL
          value: ""
        - name: DB_HOST
          value: mysql-db
        - name: DB_PORT
          value: "3306"
        - name: DB_DATABASE
          valueFrom:
            configMapKeyRef:
              key: MYSQL_DATABASE
              name: mysql-config
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              key: MYSQL_USER
              name: mysql-secret
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: MYSQL_PASSWORD
              name: mysql-secret
  restartPolicy: Always