apiVersion: v1
kind: Secret
metadata:
  name: nomadd-secret
  namespace: nomadd-stg
type: Opaque
stringData:
  APP_KEY: "base64:IrQ2ADo17OkkaOwsSPxrBoVKoH8mfrpIbex8ctPfGR4="
  REDIS_PASSWORD: "null"
  MAIL_USERNAME: "null"
  MAIL_PASSWORD: "null"
  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""
  PUSHER_APP_KEY: ""
  PUSHER_APP_SECRET: ""
  MIX_PUSHER_APP_KEY: "${PUSHER_APP_KEY}"