apiVersion: v1
kind: ConfigMap
metadata:
  name: nomadd-configmap
  namespace: {{ .Values.namespace }}
data:
{{- range $key, $value := .Values.configMap.appConfig }}
  {{ $key }}: "{{ $value }}"
{{- end }}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: {{ .Values.namespace }}
data:
{{- range $key, $value := .Values.configMap.mysqlConfig }}
  {{ $key }}: "{{ $value }}"
{{- end }}
