apiVersion: v1
kind: Pod
metadata:
  name: {{ .Values.pods.mysql.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: mysql
spec:
  containers:
    - name: mysql-db
      image: {{ .Values.pods.mysql.image }}
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: {{ .Values.services.mysql.port }}
      envFrom:
        - configMapRef:
            name: mysql-config
            optional: false
        - secretRef:
            name: mysql-secret
            optional: false
  restartPolicy: Always

---

apiVersion: v1
kind: Pod
metadata:
  name: {{ .Values.pods.nomadd.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: nomadd-stg
spec:
  initContainers:
    - name: artisan-migrate
      image: {{ .Values.pods.nomadd.image }}
      command: {{ toJson .Values.pods.nomadd.initContainerCommand }}
      env:
        - name: DB_HOST
          value: mysql-db
        - name: DB_PORT
          value: "3306"
        - name: DB_DATABASE
          valueFrom:
            configMapKeyRef:
              key: MYSQL_DATABASE
              name: mysql-config
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              key: MYSQL_USER
              name: mysql-secret
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: MYSQL_PASSWORD
              name: mysql-secret
  containers:
    - name: nomadd
      image: {{ .Values.pods.nomadd.image }}
      imagePullPolicy: IfNotPresent
      resources:
        requests:
          cpu: 100m
          memory: 500Mi
        limits:
          cpu: 1500m
          memory: 1000Mi
      ports:
        - containerPort: {{ .Values.services.nomadd.targetPort }}
      envFrom:
        - configMapRef:
            name: nomadd-configmap
        - secretRef:
            name: nomadd-secret
      env:
        - name: APP_URL
          value: ""
        - name: DB_HOST
          value: mysql-db
        - name: DB_PORT
          value: "3306"
        - name: DB_DATABASE
          valueFrom:
            configMapKeyRef:
              key: MYSQL_DATABASE
              name: mysql-config
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              key: MYSQL_USER
              name: mysql-secret
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: MYSQL_PASSWORD
              name: mysql-secret
  restartPolicy: Always
