apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: {{ .Values.namespace }}
stringData:
{{- range $key, $value := .Values.secret.mysql }}
  {{ $key }}: "{{ $value }}"
{{- end }}

---

apiVersion: v1
kind: Secret
metadata:
  name: nomadd-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
{{- range $key, $value := .Values.secret.nomadd }}
  {{ $key }}: "{{ $value }}"
{{- end }}
