apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.mysql.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: mysql
  ports:
    - port: {{ .Values.services.mysql.port }}
      name: socket
      targetPort: {{ .Values.services.mysql.port }}
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.nomadd.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: nomadd-stg
  ports:
    - port: {{ .Values.services.nomadd.port }}
      name: http
      protocol: TCP
      targetPort: {{ .Values.services.nomadd.targetPort }}
  type: NodePort
