apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: nomadd-prod
data:
  MYSQL_DATABASE: nomadd_db
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: nomadd-prod
stringData:
  MYSQL_ROOT_PASSWORD: password
  MYSQL_USER: nomadd_user
  MYSQL_PASSWORD: nomadd_pw